version: '3.8'

services:
    gnbsim:
        image: gnbsim:latest
        privileged: true
        container_name: gnbsim
        environment:
            MCC: 208
            MNC: 93
            GNBID: 1
            TAC: '0x000001'
            SST: '1'
            SD: '010203'
            PagingDRX: 'v32'
            RANUENGAPID: 0
            IMEISV: '0000000100000101'
            MSIN: '0123456789'
            RoutingIndicator: 1234
            ProtectionScheme: 'null'
            KEY: '8baf473f2f8fd09487cccbd7097c6862'
            OPc: '8e27b6af0e692e750f32667a3b14605d'
            DNN: 'internet'
            URL: 'http://172.16.1.2:8080/'
            NRCellID: 1
            NGAPPeerAddr: '192.168.1.17'
            GTPuLocalAddr: '192.168.1.3'
            GTPuIFname: 'eth0'
        networks:
            public_net_ngap:
                ipv4_address: 192.168.1.3
            public_net_gtpu:
                ipv4_address: 192.168.2.3
        volumes:
               - ./lib/modules/5.8.0-43-generic/kernel/drivers/net/gtp.ko:/lib/modules/5.8.0-43-generic/kernel/drivers/net/gtp.ko

networks:
    public_net_ngap:
        name: ngap
        ipam:
            config:
                - subnet: 192.168.1.0/24
    public_net_gtpu:
        name: gtpu
        ipam:
            config:
                - subnet: 192.168.2.0/24

