#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------

FROM ubuntu:20.04 as gnbsim-builder

RUN apt update && apt install make wget -y

# Installing go 1.16 for pfcp session injector
RUN wget https://dl.google.com/go/go1.16.3.linux-amd64.tar.gz && tar -xvf go1.16.3.linux-amd64.tar.gz && mv go /usr/local
RUN mkdir goproject
ARG GOROOT=/usr/local/go 
ARG GOPATH=/goproject 
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /gnbsim
COPY . /gnbsim

RUN make

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------
FROM ubuntu:20.04 as gnbsim

RUN apt update && apt install iproute2 vim iputils-ping net-tools -y

# Copying golang from builder image
WORKDIR /usr/local
RUN mkdir go goproject
COPY --from=gnbsim-builder /usr/local/go .
ARG GOROOT=/usr/local/go
ARG GOPATH=/goproject
ENV PATH=$GOPATH/bin:$GOROOT/bin:$PATH

WORKDIR /gnbsim/bin
COPY --from=gnbsim-builder /gnbsim/example/example .
COPY --from=gnbsim-builder /gnbsim/docker/scripts/example.json .
COPY --from=gnbsim-builder /gnbsim/docker/scripts/entrypoint.sh .

ENTRYPOINT ["/gnbsim/bin/entrypoint.sh"]

CMD ["/gnbsim/bin/example"]
